development:
  adapter: postgresql
  database: buckaruby
  host: localhost

acceptance:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>

production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
